version: 2.1
orbs:
  python: circleci/python@1.4.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install PlatformIO
          command: pip install --upgrade platformio
      - run:
          name: Install library
          command: |
            pio lib -g install fabiobatsilva/ArduinoFake@^0.2.2
            pio lib -g install git+https://github.com/google/googletest.git#release-1.11.0
      - run:
          name: Compile Project
          command: pio test -e test_device -e test_transport

workflows:
  main:
    jobs:
      - build
