version: 2.1
orbs:
  python: circleci/python@1.4.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install PlatformIO
          command: pip install --upgrade platformio
      - run:
          name: Install Libraries
          command: |
            pio lib -g install fabiobatsilva/ArduinoFake@^0.2.2
            pio lib -g install google/googletest@^1.10.0
      - run:
          name: Install  lcov
          command: |
            sudo apt-get update
            sudo apt-get -y install lcov
      - run:
          name: Compile Project
          command: pio test -e test_device
      - store_artifacts:
          path: coverage

workflows:
  main:
    jobs:
      - build
